### ISSUE TITLE
wdt esp8266

### ISSUE THREAD

**Issue by rhjdjcbcz** [duino-coin/duino-coin#1034]
how to disable wdt in code for esp8266?

**Comment by gsrbr** [comment]
Hello, disabling the WDT is not a feature officially supported by our codes, as this function is very useful for the correct functioning of the ESP miner, as it is responsible for unlocking/unstick the ESP in case the internet or even the pools oscillate... but if you still want to disable this feature, which is not recommended, you will have to develop your own modification of our code.

**Comment by gravedigger21** [comment]
> 
> 
> Hello, disabling the WDT is not a feature officially supported by our codes, as this function is very useful for the correct functioning of the ESP miner, as it is responsible for unlocking/unstick the ESP in case the internet or even the pools oscillate... but if you still want to disable this feature, which is not recommended, you will have to develop your own modification of our code.

A moronic decision. When you have problems with Internet access - do your computers, phones, TVs and other devices also constantly reboot every minute or continue to perform their functions, but without the Internet?

**Comment by gsrbr** [comment]
Hello @gravedigger21 but your PC, TV, Smartphone does not depend of the internet to work, and doesn't crash when the internet goes down... The WDT function it's for facilitate your life when something crash... In this case if the internet access, pool access or something on the hash calculation have some issue the WDT will restart the esp, to try to fix it... if you want to disable it, that's okay( I don't recommend it ), but you will need to start to monitoring the ESPs for see if it is crashing

**Comment by gravedigger21** [comment]
@gsrbr have you ever thought that there are devices that, in addition to mining, can also perform some useful work? For example, I built the mining code into my esp devices that collect information from sensors, transmit it further, and control external devices. And everything worked well until the problems started with your servers. Everything just stopped working due to constant reboots. wdt is not designed to deal with external factors like a ddos ​​attack in your case. It should monitor the performance of the esp controller. And what your code does - it just speaks of the crooked hands of the programmer who wrote it.
And yes, I fixed the code. Now I just check the availability of your servers periodically. If they are not available, I just skip the mining code and continue with the main work. If there is a problem with the esp controller itself, which is extremely unlikely, I find it easier to manually reboot it once a day than to have a bunch of useless non-working devices.
