### ISSUE TITLE
Xxhash is not installed - this mining algorithm will be disabled - Raspbian 32bit

### ISSUE THREAD

**Issue by alkuentrus** [duino-coin/duino-coin#1057]
Xxhash is not installed - this mining algorithm will be disabled

Hi, 
followed the instructions and got this response from miner.
Best regards,
David

**Comment by danigess** [comment]
Hi might not be the answer but is your miner working on CPU or RAM performance?
(I have the same message with an Rasperry Pi 4 and my raspberry Pi isnt connecting to the Duino-Coin wallet and isnt mining)

Found this in the FAQ:

https://github-wiki-see.page/m/revoxhere/duino-coin/wiki/FAQ

Q: What is the difference between DUCO-S1 and XXHASH?
A: DUCO-S1 is the original Duino-Coin algorithm based on SHA1 cryptographic function, it relies on the CPU to perform the calculations. Recently we've introduced multi-algo to the Duino-Coin chain. Since we like doing new things in the world instead of copying others, we've chosen XXHASH as an interesting algorithm to implement as it relies on the speed of RAM. You can read more about it on the official website. Summing up, DUCO-S1 = CPU Mining, XXHASH = RAM + CPU mining. Which one should you chose? It all depends on your equipment.

**Comment by alkuentrus** [comment]
It's a PI4. I guess it should be XXHASH :)

**Comment by alkuentrus** [comment]
pip3 install xxhash 

:)

**Comment by danigess** [comment]
Boah nice man :)

My Raspberry won't mine (connect to the pool) now its working.

Community = 1
Following stubborn youtube tutorials = 0

br Daniel
Have an awesome day

**Comment by alkuentrus** [comment]
Beware of the temperature.... It can go up to 85ºCelsius!!
use to check:
vcgencmd measure_temp

**Comment by danigess** [comment]
Have a fan installed on the rasp
current temp=61.8'C

but I will defently watch it.

Thx

**Comment by primitt** [comment]
Hello! XXHASH was disabled in general, so you wont be able to mine with it anyways. XXHASH is useless for now.
