### ISSUE TITLE
Raspberry Pi zero + Pi co mining rig

### ISSUE THREAD

**Issue by spacespy** [duino-coin/duino-coin#1076]
HI, 

We had seen that it's possible to build a pico mining rig with a Pi 4, but does anyone try to do it with a Pi zero instead of the Pi 4 ?? 

I'm looking for an ultra energy cost-less solution and the objective is to make a solar mining rig. 

thank you for your attention, 

best regards, 

Alex from France

**Comment by gsrbr** [comment]
Hello @spacespy , I believe it is possible to use a raspberry pi zero as the host of other miners(AVRs)... but the raspberry pi zero does not deal so easily with USB hubs, due to some limitations on its USB drive, I have a PI zero and have never found one compatible hub... I believe this is why we don't see many raspberries pi zero as mining hosts.

But as I said before, I believe this should be possible... And speaking a little bit about PICO, currently the latest versions of the PICO libraries are having problems running our mining code, because of this you may find some too Difficulties to mine with it, we are already trying to find the problem so that we can set up a definitive solution, but for now you can follow up on the other open issues regarding this problem

**Comment by sp4m4r** [comment]
Hi,

I'm running a setup of a Pi Zero with 7 Arduino Nano's for weeks now, without any issues. So if you can manage to connect the Picos and make them work on a Pi4 there shouldn't be any propblems. But maybe you also will be interested in this project ...

https://github.com/JK-Rolling/DuinoCoinI2C_RPI

it is using Pi4 or Zero and communicates over I2C instead of USB. Might be more usefull for your solar setup. I'm successfully running it also for more than one week now.

Edit: Since there are many known issues in using Pi Pico instead of Arduinos it would be interesting what changes you applied to use Picos ... might be helpfull for others.

**Comment by spacespy** [comment]
Thanks all for tour answers.

I'm looking about the Price and pico are cheaper than arduino nano or other ESP. 

That's why pico seems to be very usefull to try it .

**Comment by BastelPichi** [comment]
If you buy the arduino at the correct sources theyre cheaper than a pico. For me arduinos on a rpi zero worked fine.
