### ISSUE TITLE
The pool rejects the result if the hash rate is below normal

### ISSUE THREAD

**Issue by BBS215** [duino-coin/duino-coin#1217]
For arduino, a hashrate of 180-200 H/s is the norm. But if the result is too small (1-15), then the hashrate is less than 180 H/s, and the pool rejects the result, despite the fact that it is correct. I propose to make a correction to the pool code so that low values of the result are taken into account when checking the hashrate. 

```
22:44:53.915093 DEBUG: /dev/ttyUSB15: Requesting job
22:44:54.159190 DEBUG: /dev/ttyUSB15: Received: 82b1848f5583611e54d7e13bf7991322395337f6
22:44:54.159998 DEBUG: /dev/ttyUSB15: Sending job to the board
22:44:54.161154 DEBUG: /dev/ttyUSB15: Reading result from the board
22:44:54.185086 DEBUG: /dev/ttyUSB15: Result: 1
22:44:54.488576 DEBUG: /dev/ttyUSB15: retrieved feedback: BAD,Incorrect difficulty
22:44:54  avr15  ? Rejected 176/178 (99%) • 00.0s • 174 H/s ? diff 4 • ping 169ms
```

**Comment by LDarki** [comment]
![image](https://user-images.githubusercontent.com/51938450/149180932-f2c08eaa-3284-4df1-85d9-2269b224c172.png)
It depends on each pool.
[Source](https://github.com/Bilaboz/duino-coin-pools/blob/main/src/mining.js)
Because its the [pool rewards config](https://github.com/Bilaboz/duino-coin-pools/blob/main/config/poolRewards.json).

This can be fixed with some like this:

```
let minHashrateFix = (minHashrate - 25);
if (Math.sign(minHashrateFix ) == -1 || Math.sign(minHashrateFix ) == 0) minHashrateFix = 1; // If is negative or 0 sets to 1

if (hashrate < minHashrateFix ) {
```

**Comment by BBS215** [comment]
This bug does not appear since version 3.0
