### ISSUE TITLE
Cant login to wallet or any duinocoin website and app

### ISSUE THREAD

**Issue by abhinav596** [duino-coin/duino-coin#1318]
Is there any problem with  duinocoin api???

**Comment by abhinav596** [comment]
When I use a vpn it works

**Comment by LDarki** [comment]
Hi, i need more info for troubleshotting this.

Can you send me a screenshot of the developers console when you try to log-in ?
In order to open the developers console you need to:
- Press f12
- Click the Console tab
![image](https://user-images.githubusercontent.com/51938450/151512228-d2ddc135-be8c-4c76-adce-a138f02ae804.png)

**Comment by abhinav596** [comment]
![Uploading IMG_20220130_141926_1.jpg…]()

**Comment by abhinav596** [comment]
![Uploading IMG_20220130_141926_1.jpg…]()

**Comment by abhinav596** [comment]
@LDarki I cant upload the image here is the link with photo
https://ahdhddhh.blogspot.com/2022/01/blog-post.html?m=1

**Comment by abhinav596** [comment]
@LDarki Is this because i created a account to my sister with the same ip address if yes what can i do for it

**Comment by revoxhere** [comment]
Your IP is probably blocked
