### ISSUE TITLE
ESP32 can't connect

### ISSUE THREAD

**Issue by geneReeves** [duino-coin/duino-coin#1329]
**Describe the bug**

None of my ESP32's are able to connect.

**To Reproduce**
turn on any ESP32 and try to mine

**Expected behavior**
Work as it did yesterday

All was working when I left for work this morning.

**Comment by JensL70** [comment]
Have you updated to version 3.0? Since yesterday they rejecting 2.x miners... BTW. same as for AVR I2Cs regardless of the version number...

**Comment by Rusich1980** [comment]
I support the topic. ESP8266 has also stopped working correctly for me since that night. Initially, I flashed version 3.0 as soon as it was released. The board has not been working steadily all day today. I flashed it again. The result is that there is no stable connection to the Duco servers. Version 3.0

**Comment by LDarki** [comment]
Hi, you are still having this issue?

**Comment by LDarki** [comment]
No response.
I`ll close this issue.
