### ISSUE TITLE
Glory to Ukraine!

### ISSUE THREAD

**Issue by d2235** [duino-coin/duino-coin#1416]
Quote from your news: 
"... we won't be blocking any countries anymore as Duino-Coin is meant to be for everyone and "regular" people are not to blame for the conflict."
You are a cowardly community - by their silence, "regular" people turn into accomplices. Jerk off to your shitty coins, but don't think it won't affect you. Glory to Ukraine!

**Comment by revoxhere** [comment]
:((

**Comment by JordanEJ** [comment]
@revoxhere Don't listen to him

**Comment by JoshAtticus** [comment]
> Quote from your news: "... we won't be blocking any countries anymore as Duino-Coin is meant to be for everyone and "regular" people are not to blame for the conflict." You are a cowardly community - by their silence, "regular" people turn into accomplices. Jerk off to your shitty coins, but don't think it won't affect you. Glory to Ukraine!

Just because they don't block Russia from using duco services, doesn't mean they are a cowardly community. Github hasn't blocked russian devs from using their service, and I don't see you lashing out on them.

You also have to understand that not everyone in Russia supports this war, it was caused by Ukraine asking to join NATO, and Russia getting annoyed about the collapse of the Soviet Union, not the people of Russia.

Also, just so you know, lashing out on people on Github because you don't have the same opinion as them is not tolerated. Please read the [Github Community Guidelines](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines) for more information.

**Comment by LDarki** [comment]
Off-Topic, I'll close it.

**Comment by vmo64** [comment]
`:joy:`

**Comment by JoshAtticus** [comment]
![image](https://user-images.githubusercontent.com/72828296/159825903-7a314254-abc6-40b2-84bb-98737e3e3493.png)

**Comment by meltfrommeltland** [comment]
oh hi josh

**Comment by JoshAtticus** [comment]
> oh hi josh

oh hi indy
