### ISSUE TITLE
Servers not accepting shares

### ISSUE THREAD

**Issue by Crilum** [duino-coin/duino-coin#1514]
**Describe the bug**
I have a RPi 3B+ mining, and the miner says it has so and so thousand accepted shares, but on multiple wallets, it says I only have a few accepted shares, pic below.
A couple of days ago it worked perfectly and I was making about 4-5 DUCOs/day, but now it only shows 0.5 DUCOs/day... 
**To Reproduce**
1. Mine on a RPi (with fasthashing)
2. go to your wallet
3. See share mismatch

**Expected behavior**
I expected for it to show the correct amount of mined shares, on the wallet..

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.
![image](https://user-images.githubusercontent.com/91354257/171591201-c202e1c8-ff0d-46f1-8cf3-9bb05722a6b9.png)
**System (please complete the following information):**
 - OS: Raspberry Pi OS 11 Lite - armhf
 - Software: Official PC Miner
 - Version: 3.18

**Additional context**

**Comment by revoxhere** [comment]
This is caused by your miners reconnecting - data reported on the wallet shows the last connection info.

**Comment by Crilum** [comment]
But have my miners really mined *thousands* of shares since the last connection?

**Comment by Crilum** [comment]
Question: Did you guys change the reward rate recently?

**Comment by revoxhere** [comment]
Any important changes are always announced in the news section in the wallet and/or on the Discord server.
Thousands of shares you see in the miner is the total count since the start of the program. If it reconnects during mining to a different server, the value on the server starts from zero. This has no effect on the rewards though as the share count is only for visual purposes

**Comment by Crilum** [comment]
Thanks. I appreciate all your work!
