### ISSUE TITLE
RPi pico bug

### ISSUE THREAD

**Issue by tomasthedev** [duino-coin/duino-coin#1515]
**RPi pico bug**
Hello, I mining on RPi pico but on wallet it says "Incorrect Hashrate"
and on dashboard its says ""Arduino with Rigname: malina1 and Softwarename: Official AVR Miner 3.0 with Hashrate: 3116H/s is mining too fast (thats not better)."

**Is this big problem and what is this mean?**
**Can It reduce my mining?**
![image_2022-06-05_194509015](https://user-images.githubusercontent.com/80095089/172063415-5aefd8fe-5de3-4575-be54-9929033cc482.png)

**Comment by revoxhere** [comment]
Pico support is still experimental, mainly because none of the developers has one to work on optimizing the code for it. The warnings you see just tell you that some statistics are off with your miner, which is expected since the Pico is faster than a standard Arduino. If Kolka decides this device performs uncontrollably it will automatically send you an e-mail and put you on our watch list, but since a lot off people use Picos too, there shouldn't be a problem.

**Comment by tomasthedev** [comment]
> Pico support is still experimental, mainly because none of the developers has one to work on optimizing the code for it. The warnings you see just tell you that some statistics are off with your miner, which is expected since the Pico is faster than a standard Arduino. If Kolka decides this device performs uncontrollably it will automatically send you an e-mail and put you on our watch list, but since a lot off people use Picos too, there shouldn't be a problem.

Thanks revoxhere for awnser. How I can optimize code for RPi pico?
