### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by blackcamelot** [duino-coin/duino-coin#18]
Hi,
When will the server be back online?

Thank you

**Comment by revoxhere** [comment]
Hello. It will be back tommorow or the day after tomorrow, I'm not at home since a few days and won't be for a few more. Sorry for problems.

**Comment by revoxhere** [comment]
Server is back online since a few hours, closing

**Comment by blackcamelot** [comment]
Hi Robert, 
Duino coin is compatibile with Arduino due (ARM cpu)? 
Is it possible to put more Arduino in series to increase the computing power?
Thank you
--
Inviato da Libero Mail per Android mercoledì, 08 luglio 2020, 03:32PM +02:00 da Robert Piotrowski  notifications@github.com :

**Comment by revoxhere** [comment]
Hey.
I don't know about using other Arduino boards because I do not have them and can't check compatibility. Connecting Arduinos in series was possible but when we were using old algorithm about 6 months ago. It is certainly possible to connect them however but code modifications will be needed. When I'll have some time I may think about making daisy-chain miner for current arduino algorithm.

**Comment by blackcamelot** [comment]
Hi Robert,

I successfully installed the arduino mining program on arduino due (arm based), but the software connect correctly to the arduino, it shows the message "Arduino Mining thread started" (OK), but it doesn't go on it stays still on this screen, I don't see the blocks accepted. why?


Thank you


Alberto

**Comment by MrKris7100** [comment]
because that's not crypto, thats's shit. don't waste time for that

**Comment by lawal12345** [comment]
Hello please when will the server be back online
