### ISSUE TITLE
Problem with arduino mining

### ISSUE THREAD

**Issue by fellowmean5** [duino-coin/duino-coin#324]
Hello, when i mine with arduino i have problems. When 15 minutes past, it types: no device on COM3, check if it is connected. I was trying plug out/in arduino and reset program, but sometimes its help,but sometimes not

**Comment by kickshawprogrammer** [comment]
I had this problem with ESP-01 devices (ESP8266). For me, it ended up being a two part issue:

First, my hardware USB port was loose. I had to bend the pins to grab a hold of the USB device a little more firm so that the slightest breeze / vibration wouldn't knock it loose, and;

Second, after about 20 accepted hashes it would start getting garbage responses back from the server. I was able to track it down to not disposing of previously received server responses; specifically, in most cases, the difficulty value of 75 that remained in the buffer. I modified the program to perform a client.flush() command before sending the new request. This did slow down the hash-rate (as the code comments say it would) but the reliability was greatly improved (several hundred accepted hashes before losing connection again).

As for the second, however, the new 2.3 version of the code (looks virtually the same to me) seems to have fixed it. My guess is that the upload process itself had somehow been affecting the execution code... I did change the download options (Arduino IDE) to clear the entire flash when uploading the code and can now get several thousand hashes before having any issues.


I hope this helps.

**Comment by fellowmean5** [comment]
Thank you for your answer! I will test it with new version of code

**Comment by fellowmean5** [comment]
I see an error: trouble connect avr on port, check if it connected. You told, that need to change download options. How to do that?

**Comment by kickshawprogrammer** [comment]
I'm using the ESP-01 device (ESP8266) and not an Arduino board - different source code.

Also, the ESP8266 has the option I mentioned above but the Arduino does not. Do you have another USB port? Have you tried connecting to it?

**Comment by fellowmean5** [comment]
Yes, i tried a lot of ports. But every time, on 100 block, it wrote that board not connected.And i need to plug in/out board, then delete avr resources folder,and 50% it helps

**Comment by revoxhere** [comment]
Alright, if you have python installed then you can try running this version of the miner: https://github.com/revoxhere/duino-coin/blob/master/AVR_Miner.py - yanis made some corrections, maybe it'll work better. For more improvements, please stay tuned.

**Comment by fellowmean5** [comment]
![C31D9AD4-2C9C-41EB-9003-910499AFC438](https://user-images.githubusercontent.com/73715753/111741686-8cde1e80-888f-11eb-8d7c-aab0a8b8620b.jpeg)
Okay, i was trying use Your new version. It works, i have this:
P.s : connection to server error, and then autorestart
![Uploading C20D90DE-F5B7-4DBB-8B2A-DB583BDDED1A.jpeg…]()

**Comment by revoxhere** [comment]
I'll see what can be done about it

**Comment by revoxhere** [comment]
AVR Miner since commit https://github.com/revoxhere/duino-coin/commit/a1234cf5c8d7bf0937347882038ad729b4a0e310 should have no problems with automatically restarting if it encounters an error.
