### ISSUE TITLE
Pool Statistics workers

### ISSUE THREAD

**Issue by gam3t3chelectronicshobbyhouse** [duino-coin/duino-coin#5]
Not sure whats going on there I do have some Arduino's mining and a raspberry pi for fun but certainly not that many devices all is good but just noticed the workers keep creeping up for me.  Not sure if a issue but thought I would let you know.

**Comment by revoxhere** [comment]
Thanks for submitting bug report. 
We know of this issue and it's caused by our ssh tunnel provider - serveo.net. 
Problem is it doesn't close connection after disconnecting so people are still displayed as active workers even after they are disconnected. 
To fix this, we either have to wait until serveo finds a solution or we'll need to make some close connection signal for miners and wallets, but this will probably break compatiblity with older versions. Maybe we will find a better solution, but for now it'll stay as it is.
