### ISSUE TITLE
Is it possible to mine on nvidia gpu?

### ISSUE THREAD

**Issue by viktor02** [duino-coin/duino-coin#566]
Can I somehow mine on nvidia gpu graphics cards? In the miner settings, I have no choice, but the site with statistics has a client with gpu

**Comment by kaiiwaii** [comment]
It's possible, but the miner is under development. You should join the Discord server and ping me for more info. My Discord username is HGEpro#5291

**Comment by primitt** [comment]
> Can I somehow mine on nvidia gpu graphics cards? In the miner settings, I have no choice, but the site with statistics has a client with gpu 

The miner is currently in development. It will come out soon.

**Comment by Shreyas-Dev-ITB** [comment]
Hey there you asked is it possible to mine on nvidia gpu this crypto does not use any kind of GPUs infact I do not have gpu in my laptop this thing mines crypto easily without gpu it just uses only a small amount of calculating power of your computer and mines duino coin

**Comment by BastelPichi** [comment]
> Hey there you asked is it possible to mine on nvidia gpu this crypto does not use any kind of GPUs infact I do not have gpu in my laptop this thing mines crypto easily without gpu it just uses only a small amount of calculating power of your computer and mines duino coin

Don't tell wrong information. The normal miner just uses the CPU. But the gpu miner will come out soon and then you can also mine on gpu(if you have).

**Comment by no-defun-allowed** [comment]
In my opinion the difficulty doesn't go high enough to make GPU mining viable. This is probably a good thing in the end, but why this is a problem if you want to GPU mine is a side-effect of [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl's_law) in a way.

Say we had a miner which took 5 seconds to do some work, and 1 second to submit and get new work. Now, suppose we were to increase the hash rate by 10 times (which seems about right for an embarrassingly parallel problem on a GPU from experience). Now doing the work takes 0.5 seconds, but submitting and getting new work is still 1 second. So all up, we're only going 4 times as fast as before. Would we have an infinitely fast GPU, it can be observed that we'd only go 12 times as fast as with the original miner, which is quite wasteful.

Would there be more difficult work, the miner utilisation would be higher. Say, instead, the original miner took 50 seconds on the new difficulty, and the GPU miner takes 5 seconds, then we would have efficiency closer to the original miner with a much larger workload. One work-around is to establish multiple connections, so that you have more work to complete without having to wait, but then the system penalises you for seemingly using multiple PCs. This can be argued to be a feature, as it is a design goal to be competitive with small devices. Or perhaps not, because your efficiency is then basically determined by ping, would you go fast enough.

**Comment by revoxhere** [comment]
This is not a coin for fast miners. If you have powerful hardware you can mine anything else. The CPU and GPU mining is only a bonus option, to show that it's possible

**Comment by no-defun-allowed** [comment]
Right. So while it is technically possible, it is not worth the hassle to do GPU mining in my opinion.

**Comment by colonelwatch** [comment]
I thought DUCO-S1 was a nice toy problem to learn OpenCL on, and I ended up building an OpenCL miner for Duino-Coin (https://github.com/colonelwatch/nonceMiner/). I may or may not be able to polish it into a release version, but meanwhile I have to disagree and agree with the Amdahl's Law argument.

First, the server code implies that difficulty is adjusted on-the-fly with the goal of making the expected share-time (work time + network delays) 10 seconds (see https://github.com/revoxhere/duino-coin/blob/useful-tools/Master_Server/Server.py#L1284-L1285). IIRC, this was to make profits equal, but it also should defeat Amdahl's Law because the difficulty must follow the hashrate to accomplish this. _In theory, anyway._

In fact, there seems to a hole in the algorithm: the difficulty can only rise to double it's original value. Here's the difficulty multiplier from it.

```
p = 2 - sharetime / expected_sharetime
```

If the sharetime is very small, `sharetime/expected_sharetime` is approximately zero.

If difficulty no longer increases, this means that Amdahl's Law _does_ apply after that point. Case in point: running the code as of July 20th, 2021, an RTX 3070 does 1 GH/s by my benchmarks, which does not consider networking. However, it's online performance (pulse-node) is only ~200 MH/s. Moreover, I noticed the difficulty cap out at about 1.8 million, double from starting around 900000.

That said, Amdahl's Law coming into play also means that the algorithm has failed. I observed a fast sharetime of about 0.5 seconds: not much but the network delay from here in America. As a result, the RTX 3070 produces about 30 DUCO per day even on EXTREME difficulty, the most out of any device. Beyond that, I've seen nothing in the server code that penalizes just 5 connections, which should be all I need in this case. So, 150 DUCO per day may be possible.

Edit: Anyway, I'm not going to use an RTX 3070 for this in the long term, but my hopes with my new OpenCL miner is that people can unlock the free performance hiding in their GPUs. (My laptop's Intel UHD 630 Graphics does about 50 MH/s!)

**Comment by no-defun-allowed** [comment]
From previous tests, efficiency does decrease even at 5 connections; I found the sweet spot to be 3 connections with a RX 580 (which also gets about 1.4GH/s on xxhash after some tweaking). This nets some 60 to 80 DUCO/day depending on how hard you breathe on the wallet statistics or something like that :)

> IIRC, this was to make profits equal, but it also should defeat Amdahl's Law because the difficulty must follow the hashrate to accomplish this. In theory, anyway.

Right, this is what I was getting at by increasing the difficulty, though I didn't look for the server code to back up my statement that the difficulty wouldn't go high enough. And yes, I've only seen the difficulty go up to just over 1.8 million too.

Would we also read the [kolka_v1](https://github.com/revoxhere/duino-coin/blob/4abb3ff9499c060a9882f88dc03f6ef324f420d8/Master_Server/kolka_module.py#L23) function which computes the pay-out, any difficulty over 350,000 is going to lead to quite low results anyway.

**Comment by revoxhere** [comment]
I'm still surprised how many people don't get the point/goal of this coin

**Comment by no-defun-allowed** [comment]
I'm only saying that's why it would be a bad idea to GPU mine, not that it is bad that it is a bad idea to GPU mine.

**Comment by YeahNotSewerSide** [comment]
> Moreover, I noticed the difficulty cap out at about 1.8 million, double from starting around 900000.

on my laptop gpu with 50 mh/s  difficulty can raise up to 10mil. While writing gpu miner, we had tester with 3070, he had 3 gh/s, difficulty was so big at some point it overflowed unsigned long, so difficulty can raise significantly if you have high hashrate. Tested with sha1 btw.

**Comment by colonelwatch** [comment]
@DoctorEenot When did you achieve that? What were the conditions? I've never observed anything more than double, but that would be a difficulty of ten times more. 

That kind of difficulty scaling is necessary to maximize GPU work (or else to make GPU and CPU more equitable: the reward policy per share is the project's decision). Otherwise, a low difficulty like 1.8 million will cause higher than expected share-rates _and_ lost efficiency because of Amdahl's law.

(My use of language around Amdahl's Law may have been confusing before. The above is what I mean.)

**Comment by YeahNotSewerSide** [comment]
> 
> 
> @DoctorEenot When did you achieve that? What were the conditions? I've never observed anything more than double, but that would be a difficulty of ten times more.
> 
> That kind of difficulty scaling is necessary to maximize GPU work (or else to make GPU and CPU more equitable: the reward policy per share is the project's decision). Otherwise, a low difficulty like 1.8 million will cause higher than expected share-rates _and_ lost efficiency because of Amdahl's law.
> 
> (My use of language around Amdahl's Law may have been confusing before. The above is what I mean.)

Yeah, sorry, I tested with pool, there is clearly something wrong with pool, I was getting these diff straight from server.

**Comment by YeahNotSewerSide** [comment]
@colonelwatch I answered some things about opencl miner in pull request, mention to which you sent.

**Comment by colonelwatch** [comment]
I just released nonceMiner v2.1.0 (https://github.com/colonelwatch/nonceMiner/releases) with initial OpenCL support, so people can start using GPUs... well, ahead of the official miner anyway.

**Comment by revoxhere** [comment]
XD nice, firstly leave the dev team and then do your thing

> I just released nonceMiner v2.1.0 (https://github.com/colonelwatch/nonceMiner/releases) with initial OpenCL support, so people can start using GPUs... well, ahead of the official miner anyway.

**Comment by primitt** [comment]
> XD nice, firstly leave the dev team and then do your thing
> 
> > I just released nonceMiner v2.1.0 (https://github.com/colonelwatch/nonceMiner/releases) with initial OpenCL support, so people can start using GPUs... well, ahead of the official miner anyway.

He was part of the dev team?

**Comment by no-defun-allowed** [comment]
They yoinked code from the dev team? It's very nearly an afternoon project if you have literally nothing else to do.

**Comment by colonelwatch** [comment]
> He was part of the dev team?

I helped them fix a couple big bugs in their server, and they gave me a dev role on Discord. But I decided to leave because I didn't feel comfortable being there while maintaining nonceMiner at the same time. It felt like a huge conflict of interest.

> They yoinked code from the dev team? It's very nearly an afternoon project if you have literally nothing else to do.

Absolutely not. The SHA1 OpenCL code I used was open source, and I wrote the rest of the code. If you added up the hours here and there, I guess you could say it was an afternoon! That said, I wasted much more time trying to optimize it.

**Comment by revoxhere** [comment]
See, travelmode is so smart he made a miner, go use it, he's superior. Closing
