### ISSUE TITLE
why are cloud services banned?

### ISSUE THREAD

**Issue by VatsaDev** [duino-coin/duino-coin#568]
why, could it be explained ->

Mining with free cloud hosting services (or free VPS services - e.g. Repl.it, GitHub Actions, etc.) is not allowed.

because the difficulty would adjust if i used a nodejs miner or something, so whats the reason?

**Comment by revoxhere** [comment]
Difficulty has nothing to do with it and is automatically adjusted for all devices.
The reason is that it's not fair for other miners, which is the main goal of Duino-Coin.

**Comment by BastelPichi** [comment]
> why, could it be explained ->
> 
> Mining with free cloud hosting services (or free VPS services - e.g. Repl.it, GitHub Actions, etc.) is not allowed.
> 
> because the difficulty would adjust if i used a nodejs miner or something, so whats the reason?

Also you dont pay for it, so its bassically also abusing the platforms.

**Comment by LolloDev5123** [comment]
I am trying to implement DUCO Mining in Roblox, using the Lua programming language.
The problem is that the platform does not support https requests nor websockets, so I have to use a proxy such as repl.it to connect to the websocket and check messages using long polling on Roblox.

Unless there is a way for devices to mine using REST HTTP Requests, I won't be able to do this

**Comment by BastelPichi** [comment]
Hello,
Using an tool like replit as an proxy is allowed. (It might fail the proxy detection tho). As something like this can be very prone to errors, I'd recommend getting a proper, cheap vps (or even free - oracle free cloud tier).
