### ISSUE TITLE
Too many workers?

### ISSUE THREAD

**Issue by Magillagorilla778** [duino-coin/duino-coin#606]
Hey everyone,
I keep getting a "Server message: Too many workers" error. Am I only limited to a certain amount of miners? 

**System (please complete the following information):**
 - Raspberry Pi OS 32Bit
 - PC_Miner
 - 2.5

**Additional context**

**Comment by Verus1989** [comment]
me too

**Comment by gottodin2008** [comment]
i have the same problem.

**Comment by manojj006** [comment]
i have same problem

**Comment by liubergarcia** [comment]
i have the same problem and i only have a pc + 1 Arduino one .how to fix it?

**Comment by esp220221** [comment]
Same issue

**Comment by revoxhere** [comment]
Please try again now

**Comment by esp220221** [comment]
It's working again.  Thank you @revoxhere

**Comment by gottodin2008** [comment]
The problem is still there. According to the APP, 25 miners are active and registered, but they don't mean it. It always says: Server massage: to many workers.

System: Win10
AVR, PC Mining 2.5.1
Miner: Arduino uno + Nano, PC(Intel), Raspberry Pi4b
![Screenshot_20210629_115459_com pripun duinocoin](https://user-images.githubusercontent.com/86598156/123778852-d6e49080-d8d1-11eb-8dd5-6fcf0e4de85b.jpg)
![Unbenannt](https://user-images.githubusercontent.com/86598156/123778894-e368e900-d8d1-11eb-8d16-19b0c5a07bcc.jpg)

**Comment by revoxhere** [comment]
Looks like because of often restarts, they stay in the worker list and thus count towards the counter

**Comment by gottodin2008** [comment]
> Looks like because of often restarts, they stay in the worker list and thus count towards the counter

and how can i fix the Problem?

**Comment by revoxhere** [comment]
should be fixed now
