### ISSUE TITLE
Walet dont show amount of coins stay in fetching data when you turn to landscape and back to regular dont shows the screen in the proper way 

### ISSUE THREAD

**Issue by liubergarcia** [duino-coin/duino-coin#713]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/photos**
If applicable, add screenshots or photos to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Windows]
 - Software [e.g. AVR Miner]
 - Version [e.g. 2.4]

**Additional context**

**Comment by gsrbr** [comment]
Hello, 

1. The Duino Coin servers are overloaded because of this, parts of the server are not respond correctly like the REST-api who is used for show the somethings on the wallet(like amount of coins).
 
2. The design error is something that should be studied more calmly, let's wait for the developers to verify this

**Comment by revoxhere** [comment]
Nice issue template usage xD
