### ISSUE TITLE
What's the maximum connections of ESP8266

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#775]
Hi! Good day! Do you know what is the maximum connection limit of the official ESP8266 miners for an  Duino-Coin account? I borrowed 30 pcs of ESP8266 boards, but failed to connect all boards to the DUCO Server. Only 25 boards were allowed for mining at the same time. Is it meaning that only accept 25 pcs of ESP8266 boards for mining at the moment? 

Also there has connection error now, maybe server down......

**Comment by gsrbr** [comment]
Hello,

The server don't have a limit of miners but you can see on the [useful-tools branch](https://github.com/revoxhere/duino-coin/tree/useful-tools) this information -> **Make sure you don't create more more than 50 connections in time shorter than 30 seconds. If you do that, the server may ban your IP for creating too much traffic and being a potential DDoS attacker.**

And remember of the Kolka system
<html>
<body>
<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span></span>Since introduction of Kolka system V4, each miner earns a bit less than the previous one to prevent that. Why? It's the best compromise for having small and big miners on the network. Here's a table for the earnings after being affected by Kolka (may be adjusted a bit in the future):</p>

Worker | worker earnings (AVR) | worker earnings (PC)
-- | -- | --
1 | 100% | 100%
2 | 96% | 80%
3 | 92% | 64%
4 | 88% | 51%
5 | 84% | 40%
6 | 81% | 33%
7 | 75% | 26%
n | 96% of n-1 earnings | 80% of n-1 earnings

<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Does that mean more miners = more earnigs? No, just lower efficiency of them.</p>
</body>
</html>



And yes, the Duino coin system are with some problems on the servers

**Comment by marcoduinocoin** [comment]
Hi Gsrbr! Thanks for your helpful message. Exactly what really happened to me. Thank you so much.
