### ISSUE TITLE
Avr mining is disabled

### ISSUE THREAD

**Issue by TusharChillal** [duino-coin/duino-coin#905]
Avr mining is disabled

How do I enable 

__Originally posted by @revoxhere in https://github.com/revoxhere/duino-coin/issues/904#issuecomment-907168930__

**Comment by daanbreur** [comment]
I dont know if you are actually asking this or if its a joke....

**Comment by n0t-f0ur13r** [comment]
If u didn't knew, DUCO mining has been disabled for a while, mining with ESP boards and PCs is available, but AVR mining still isn't.

**Comment by Diksrifa** [comment]
Why can't esp8266 connect to the server... I tried to flash again the result is still the same I can't connect to the server

**Comment by TusharChillal** [comment]
like by when can it be enabled

**Comment by Izder456** [comment]
@Tushkiller is this a joke? the _server_ shut down AVR mining, so there's _nothing_ you can do on your end. We just have to wait till the fixes are pushed out to combat the ginormous emulator/real hw rigs, killing the chain.

**Comment by gsrbr** [comment]
Hello @Tushkiller , AVR mining is temporarily disabled due to some issues, we are working hard to develop the solutions so we can go back to mining normally, as it was said earlier in this issue the ESP and PC mining is working normally. If your question has been resolved:heavy_check_mark:, please close this issue:smile:

Heyy @Diksrifa try to use the [latest version of the code](https://github.com/revoxhere/duino-coin/tree/master/ESP8266_Code), it should probably work, if it doesn't work  enter our [discord ](https://discord.gg/kvBkccy)server and ask for help in the #help channel or open another issue (because this is to discuss why avr is disabled)
