### ISSUE TITLE
Raspberry Pi 4 Thread Processor Reduced (Not sync with PC_Miner.conf file)

### ISSUE THREAD

**Issue by ururumpo** [duino-coin/duino-coin#923]
i got issue on my raspberry pi 4. that say my miner only 3 threads active sometimes only 1.
for first time miner launch, yes it is 4 Threads active, but after few minutes/hours Threads reduced. sadly never back to 4 Threads
but im sure in configuration file i set 4 Thread with Algo DUCO-S1.
my RPi4 temp always 30 - 42c (with active cooling fan)
im using latest miner 2.7.
i dont know, this issue from my side or from script miner or server.
![Screenshot_20210830-075038](https://user-images.githubusercontent.com/89758493/131278206-7b9d1342-7f7c-4167-8d17-54ec5335b4da.png)

**Comment by gsrbr** [comment]
Hi, I don't remember the exact time, but for a miner appear in this tab it has to mine more than once in a certain period of time so that the system knows it is operating, what could be happening is that the time among the hashs mined in your miner is so large that the system does not recognize it for viewing in the api/wallet
One way to confirm that all threads are mining correctly is to check the terminal while mining.
I hope I have resolved your doubts, if yes please close this issue

**Comment by ururumpo** [comment]
> Hi, I don't remember the exact time, but for a miner appear in this tab it has to mine more than once in a certain period of time so that the system knows it is operating, what could be happening is that the time among the hashs mined in your miner is so large that the system does not recognize it for viewing in the api/wallet
> One way to confirm that all threads are mining correctly is to check the terminal while mining.
> I hope I have resolved your doubts, if yes please close this issue

~~im already check the terminal while mining. they are all forced decreased until 1 threads active.
what i know, 700khz-1mhz is normal for 4 threads rpi (low diff).
2.7 i think not optimized for rpi. start from 2.7 is full code rewrite right?~~
~~*I will leave this issue open until there is good progress~~
UPDATE : testing new version PC_Miner 2.7.1 that is looking good for my RPI overnight.
all treads stable
hashrate?? let say... in this version stable 68x khs. never go higher 7xx++ khs until 1 mhs.
nothing wrong, except while server down or api error.
rewards?? waiting for good progress. it's still Logarythmic 🤷
