### ISSUE TITLE
Raspberry Pi Pico

### ISSUE THREAD

**Issue by dapiced** [duino-coin/duino-coin#969]
Hi, i have flashed my **Raspberry pi** **pico** with file : **Arduino_Code.ino**.  Everything went ok but when i start the **AVR_Miner.py** it stuck at :

`
sys0 AVR mining thread is starting using DUC0-S1A algorithm (/dev/ttyACM0)
`

**DEBUG MODE** 

`18:51:50  sys0  AVR mining thread is starting using DUCO-S1A algorithm (/dev/ttyACM0)   `
`18:51:50.730439 DEBUG: /dev/ttyACM0: requested job from the server  `
`18:51:50.827409 DEBUG: Received: ['75064b256f9eed1bf9ef3850656d4cfbdec22715', '91c14375eda1a999c7e2c4f6e63a1bfea55b4e03', '6']    `
`18:51:50.827667 DEBUG: 0Correct job received  `
`18:51:50.827741 DEBUG: /dev/ttyACM0: sending job to AVR  `

Also the green LED of the pico flash like that : 3 times slow flash follow by 5 times fast flash :  _ _ _ .....

Something i forgot ?

Thanks
Dominic

**Comment by sp4m4r** [comment]
I was facing the same issue, I think you did nothing wrong. As far as I found, Pico was removed for now, maybe temporary, maybe permanently, most likely due to problems with the unique ID issue. See history of:

[https://github.com/revoxhere/duino-coin/blob/master/Arduino_Code/uniqueID.h](url)

But it would be interesting if Pico Support is planned for the future again. Kind regards.

**Comment by dapiced** [comment]
Thanks for the infos.!
